name: CRON
on:
    schedule:
        - cron: "*/5 * * * *"

jobs:
    update-schemastore:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
            - name: Install Packages
              run: npm install
            - name: Update SchemaStore
              uses: ./.github/actions/test
              id: updateSchemastore
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              with:
                  tag_name: v${{ steps.updateSchemastore.outputs.version }}
                  body: Update schema store
                  commitish: master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              if: success() && steps.updateSchemastore.outputs.updated == 1
